use chroot = no
max connections = 4
syslog facility = local5
pid file = %RSYNC_USER_NAME%/.local/state/rsync/rsyncd.pid
port = 8730

[m]
path = %RSYNC_USER_NAME%/incoming/rsync
lock file = %RSYNC_USER_NAME%/.local/state/rsync/m.lock
read only = no
list = yes
timeout = 300

