#font=monospace:size=22
font=Linejoy-Regular:size=17,DejaVu Sans Mono:size=17

[key-bindings]
scrollback-up-page=KP_Page_Up Page_Up
scrollback-down-page=KP_Page_Down Page_Down
Insert = RUN: \e[2u


[scrollback]
lines=2000

