use chroot = no
max connections = 4
syslog facility = local5
pid file = /home/%RSYNC_USERNAME%/.local/state/rsync/rsyncd.pid
port = 8730

[m]
path = /home/%RSYNC_USERNAME%/incoming/rsync
lock file = /home/%RSYNC_USERNAME%/.local/state/rsync/m.lock
read only = no
list = yes
timeout = 300

