#font=monospace:size=22
font=Linejoy-Regular:size=14,DejaVu Sans Mono:size=17

initial-color-theme=dark
[colors-dark]
alpha=1.0
foreground=ffffff
background=000000

[key-bindings]
scrollback-up-page=KP_Page_Up Page_Up
scrollback-down-page=KP_Page_Down Page_Down


[scrollback]
lines=2000

