vim9script
#{{{ core settings

:set runtimepath=~/.config/vim
:set foldmethod=marker
:set tabstop=3
:set softtabstop=0
:set smarttab
:set expandtab
:set smartindent
:set ignorecase
:set clipboard=unnamedplus
:set shiftwidth=3
:set wrap
:set linebreak
syntax on
g:mapleader = ","
# line numbers:
:set nu
:set rnu
# disable startup screen
:set shm+=I
# allow having inactive buffers in the same window as the active
:set hidden
# Break away from Vi compatibility
:set cpoptions=aABceFsz
# color scheme:
:set termguicolors
:hi LineNr guibg=#000000 guifg=#ffffff
:hi CursorLineNr guibg=#000000 guifg=#ffffff
:hi Comment guibg=#000000 guifg=#00ff00
:hi Keyword guibg=#000000 guifg=#ffff00
:hi Search ctermbg=8
:hi Normal guibg=#000000 guifg=#ffffff
:hi NormalFloat ctermbg=0
:hi Folded guibg=#242424 guifg=white

# cursor line's colors
:hi CursorLine guibg=#000000 guifg=white cterm=NONE
:hi CursorLineNr cterm=NONE
:set cursorline
autocmd InsertLeave * highlight CursorLine guibg=#000000
autocmd InsertEnter * highlight CursorLine guibg=#303030

:set showcmd
:set laststatus=2
# see ":h statusline" for explanation
:set statusline=%-t%m%=%c%=%P%S

#}}}
#{{{core keybindings

inoremap <silent> <Tab> <Esc>
inoremap <silent> <C-space> <space><space><space>

inoremap <silent> <C-s> <Esc>:wa<CR>
nnoremap <silent> <C-s> <Esc>:wa<CR>

# space in normal mode
nnoremap <silent> <space> i<space><Esc> 
# buffers (next, previous, previous visited)
nnoremap <silent> <C-n> :bn<CR>
nnoremap <silent> <C-p> :bp<CR>
nnoremap <silent> <C-3> :b#<CR>

nnoremap <silent> L 21l
nnoremap <silent> H 21h
nnoremap <silent> x "_x

nnoremap <silent> O O<Esc>
nnoremap <silent> o o<Esc>

# copy and paste
vnoremap <silent> y "+y
nnoremap <silent> Y "+Y
vnoremap <silent> <C-c> "+y
nnoremap <silent> <C-v> "+p
inoremap <silent> <C-v> "+p

nnoremap <f9> :make testParser<CR><CR><CR>:cwindow<CR>



#}}}
#{{{ utils

def GetCurrLineNum(): number
   return line(".") - 1
enddef

def GetVisualLineInterval(): tuple<number, number>
   var vstart = getpos("'<")
   var vend = getpos("'>")
   return (vstart[1] - 1, vend[1])
enddef


def GetCurrLine(): string
   return getline(".")
enddef

def GetLine(i: number): string
   return getline(i + 1)
enddef

def SetLine(i: number, newVal: string)
   call setline(i + 1, newVal)
enddef

def GetCountLines(): number
   return line('$')
enddef

def InsertLineAfter(afterInd: number, newLineContent: string)
   call append(afterInd + 1, newLineContent)
enddef


#}}}
#{{{custom functions

# Comment out multiline visual selection, or remove comments from a block
def g:CommentOrUncomment()
   var visualLineInt = GetVisualLineInterval()
   var msg = "line " .. visualLineInt[0] .. " to " .. visualLineInt[1]
   var i = visualLineInt[0]
   while i < visualLineInt[1]
      var line = GetLine(i)
      SetLine(i, "//~" .. line)
      i = i + 1
   endwhile
enddef

vnoremap <silent> <C-e> :<C-u>call CommentOrUncomment()<CR>

# Go to definition of a C element
def g:GoToCDef()
   var name = expand("<cword>") # word under cursor
   var theCommand = ":bufdo silent! lvim /:" .. name .. "/ %"
   exe theCommand
enddef

nnoremap <silent> <C-d> :call GoToCDef()<CR>

#}}}
#{{{snippets

# Alternative way of defining a command
#command -nargs=0 CommentOrUncomment call CommentOrUncomment() 
#vnoremap <silent> <C-e> :<C-u>CommentOrUncomment<CR>

# Cursor?
#set t_SI="\<Esc>[6 q"

#set t_SI="\<Esc>]12;purple\x7"
#set t_SR="\<Esc>]12;red\x7"
#set t_EI="\<Esc>]12;green\x7"

#}}}
