use chroot = no
max connections = 4
syslog facility = local5
pid file = $HOME/.local/state/rsync/rsyncd.pid
port = 8730

[m]
path = $HOME/incoming/rsync
lock file = $HOME/.local/state/rsync/m.lock
read only = no
list = yes
timeout = 300

