theme = "onedark"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
tab = "normal_mode"
C-w = ":write-all"

[keys.normal]
C-p = ":buffer-next"
C-n = ":buffer-previous"
#";" = "space_mode"

